config/routes.rb
Rails.application.routes.draw do

root 'pages#index'

get '/track/new' => 'track#new', as: :new_track
post '/tracks' =>'track#create'
get '/tracks/:id/edit' => 'track#edit', as: :edit_track
patch 'tracks/:id' => 'track#update', as: :track

get '/map' => 'pages#map'


get '/tag/new' => 'tag#new', as: :new_tag
post '/tags' =>'tag#create'

get '/tracktag/new' => 'track_tag#new', as: :new_tracktag
post '/track_tags' =>'track_tag#create'

get '/track/find/:id' => 'track#find', as: :closest


end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :track_tags
  has_many :tracks, through: :track_tags
end

app/models/track.rb
class Track < ActiveRecord::Base
  has_many :track_tags
  has_many :tags, through: :track_tags 


  def self.find_closest_1(id)     #this is the most rudimentary "most tags matched" function
    master = Track.find(id)             #this is the incoming track
    tag_number = master.tags.length     #this is how many tags it has
    tracks = Track.all
    top_track = []
    top_score = 1                       #at least 1 tag must match

    tracks.each do |t|      # cycle through each track
      score = 0
      unless t.id == master.id  #exclude the incoming track from calculations (otherwise, perfect similarity with self)
        puts "Now examining #{t.name}"
        t.tags.each do |tag|      #for this track, cycle through each tag 
          score +=1 if master.tags.include? tag
          puts "The current score is #{score}"
        end

        if score >= top_score 
          puts "*BOOM!* - top track is now #{t.name} because #{score} is bigger than #{top_score}"
          top_score = score

          top_track.push([t, top_score])    # !! we're pushing the similarity score, then the track
        end
      end
    end

    #The major problem here is that every new track ups the top_score to beat. So, an early low-matching track can sneak in
    # and stay there, but a high-matching early track means no others can break through. ex: 1/1/2/6 vs 6......

    puts "============= SEARCH IS OVER ============="

    top_track.sort!.reverse!        #sort by the top scores, reverse.      

    return top_track

  end

  def self.find_closest_2(id)
    master = Track.find(id)             #this is the incoming track
  end

def self.find_similarity(other_track)


end


end

app/models/track_tag.rb
class TrackTag < ActiveRecord::Base
  belongs_to :track
  belongs_to :tag
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/mazes_controller.rb
class MazesController < ApplicationController

  def find
    @result = Track.find_closest_1(params[:id])
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  

  def index

=begin    
	@tracks = Track.all
=end

#    @tracks = AWS::S3::Bucket.find('nebula-alpha').objects
    @tracks = Track.all
  end


  def map
    gon.tracks = Track.all
  end


end

app/controllers/tag_controller.rb
class TagController < ApplicationController
  
  def new
    @tag = Tag.new
  end

  def create
    @tag = Tag.new(tag_params)
    if @tag.save
      redirect_to new_tag_path
    else
      redirect_to new_tag_path
    end
  end

  private

  def tag_params
    params.require(:tag).permit(:name, :slow, :acoustic)
  end

end

app/controllers/track_controller.rb
class TrackController < ApplicationController

  def new
    @track = Track.new
  end

  def create
    @track = Track.new(track_params)
    if @track.save
      redirect_to root_path
    else
      redirect_to new_track_path
    end
  end

  def find
    @track = Track.find_closest_1(params[:id])  #this'll change based on which algorithm we're using
  end


  def edit
    @track = Track.find(params[:id])
  end


  def update
    @track = Track.find(params[:id])
    if @track.update_attributes(track_params)
      redirect_to root_path
    else
      redirect_to edit_track_path(params[:id])
    end
  end




  private

  def track_params
    params.require(:track).permit(:name, :artist, :album, :url, :slow, :acoustic, tag_ids: [])  #note how I'm handling the array of tag ids here!
  end


end

app/controllers/track_tag_controller.rb
class TrackTagController < ApplicationController

 def new
    @tracktag = TrackTag.new
    @tags = Tag.all
    @tracks = Track.all
  end

  def create
    @tracktag = TrackTag.new(track_tag_params)
    if @tracktag.save
      redirect_to root_path
    else
      redirect_to new_tracktag_path
    end
  end

  private

  def track_tag_params
    params.require(:track_tag).permit(:track_id, :tag_id)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper

	def download_url_for(song_key)
	    AWS::S3::S3Object.url_for(song_key, 'nebula-alpha', :authenticated => false)
	end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/tag_helper.rb
module TagHelper
end

app/helpers/track_helper.rb
module TrackHelper
end

app/helpers/track_tag_helper.rb
module TrackTagHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Nebula</title>

  <!-- LINKING BOOTSTRAP IS BAD -->

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= include_gon(:init => true) %>
    <%= Gon::Base.render_data({}) %>

    
</head>
<body>


	<%= link_to image_tag("logo.jpg", size: "80"), root_path %> <h1>Welcome to Nebula V 0.02 </h1>
    
    <h2 class = "subtitle">Last updated: Oct 15, 2016</h2>

    <div class = "header">
        <%= link_to "New track", new_track_path %>
        <%= link_to "New tag", new_tag_path %><br>
        <%= link_to "New track tag", new_tracktag_path %>
        <%= link_to "Explore the Map", map_path %>
    </div>

	<%= yield %>

	<br>
	<br>
</body>
</html>

app/views/pages/index.html.erb
<!-- this whole section is commented out -->

<% if false %>

<% @tracks.each do |song| %>
	<li><%= link_to song.key, download_url_for(song.key) %> </li>
<% end %>


<% end %>

<div class = "row">
    <% @tracks.each do |t| %>
        <p>
            Name: <%=  link_to t.name, closest_path(t.id) %>, tags: <%= t.tags.length %> 
            <%= link_to "[edit]", edit_track_path(t.id) %>
            Tags: <% t.tags.each do |g| %>
                <%= g.name %>
            <% end %>
        </p>
    <% end %>
</div>

app/views/pages/map.html.erb
        <!-- 

        <div id = "status"></div>
        <div id = "count"></div>



        <div>Animating: <span id = "animating"></span></div>
        <div>Visible circles: <span id = "visible"></span></div>
        <div>Position: (<span id = "x-pos"></span>, <span id = "y-pos"></span>)</div>
        <div>Last click: (<span id = "click-xpos">0</span>, <span id = "click-ypos">0</span>)</div>
        <br>
        <br>

         -->

         <div class = "row">

             <div class = "col-md-3">
                 <div class = "song-card">
                    <span id = "song">-</span>
                    <span id = "artist">-</span>
                    <span id = "album">-</span>
                    <span id = "tags"></span>
                </div> 
                <div class = "controls">
                    <span id = "play" class="glyphicon glyphicon-play" aria-hidden="true"></span>
                    <span id = "stop"  class="glyphicon glyphicon-stop" aria-hidden="true"></span>

                </div>
             </div>

             <div class = "col-md-9">
                <canvas id="canvas" width="1000" height="562.5"></canvas>
             </div>
         </div>
        

       

app/views/tag/new.html.erb
<h2>Create new tag:</h2>

<br>

<%= form_for @tag do |t| %>
   
    Name:
    <br>
    <%= t.text_field :name %>
    <br>
    Slow: <%= t.text_field :slow %>
    <br>
    Acoustic: <%= t.text_field :acoustic %>
    <br>
    <%= t.submit "Create tag" %>

<% end %>

app/views/track/edit.html.erb
<h2>Settings for <%= @track.name %></h2>

<%= form_for @track do |t| %>

    <br>Name:
    <br><%= t.text_field :name %>
    <br>Artist:
    <br><%= t.text_field :artist %>
    <br>Album:
    <br><%= t.text_field :album %>
    <br>Slow:
    <br><%= t.text_field :album %>
    <br>Album:
    <br><%= t.text_field :album %>
    <br>Slow (0-100):
    <br><%= t.text_field :slow %>
    <br>Acoustic (0-100):
    <br><%= t.text_field :acoustic %>

    <br>
    <h5>Tags: </h5>

    <% Tag.all.each do |tag| %>

        <%= check_box_tag "track[tag_ids][]", tag.id, @track.tags.include?(tag)  %>
        <%= tag.name %>
        <br>
    <% end %>
    
  <%= t.submit "Update preferences" %>
<% end %>

app/views/track/find.html.erb
<h2>The closest track to <%= Track.find(params[:id]).name %> is:</h2>

<% @track.each do |t| %>

<p>
    <%= link_to t[0].name, closest_path(t[0].id) %>
    <br>
    Similar tags: <%= t[1] %>
    <br>
</p>

<% end %>

app/views/track/new.html.erb
<h2>Create new track:</h2>

<%= form_for @track do |t| %>

    <br>Name:
    <br><%= t.text_field :name %>
    <br>Artist:
    <br><%= t.text_field :artist %>
    <br>Album:
    <br><%= t.text_field :album %>
    <br>URL:
    <br><%= t.text_field :url %>
    <br>Slow (0-100):
    <br><%= t.text_field :slow %>
    <br>Acoustic (0-100):
    <br><%= t.text_field :acoustic %>

    <br>
    <h5>Tags: </h5>

    <% Tag.all.each do |tag| %>

        <%= check_box_tag "track[tag_ids][]", tag.id  %>
        <%= tag.name %>
        <br>
    <% end %>
    
    <%= t.submit "Create track" %>
<% end %>

app/views/track_tag/new.html.erb
<h2>Add tag to track:</h2>

<%= form_for @tracktag do |t| %>

    <table>
        <tr>
            <td>Tag</td>
            <td>Track<td>
        </tr>

        <tr>
            <% @tags.each do |s| %>

                <td><%= check_box_tag :tag_id, s.id %><%= s.name %></td>

                <!-- <td><%= t.radio_button :tag_id, s.id %><%= s.name %></td> -->

            <% end %>
        </tr>

        <tr>
            <% @tracks.each do |r| %>

                <td><%= t.radio_button :track_id, r.id %><%= r.name %></td>

            <% end %>
        </tr>
    </table>   



    <%= t.submit "Add tag to track" %>

<% end %>